<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\plugin\</OutputPath>
    <RaftManaged>E:\Raft\Raft_Data\Managed</RaftManaged>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.2.2" />
    <EmbeddedResource Include="lib\0Harmony.dll" LogicalName="0Harmony.dll" />
  </ItemGroup>
  <Target Name="EnsureHarmonyLib" BeforeTargets="PrepareForBuild">
    <MakeDir Directories="$(MSBuildProjectDirectory)\lib" />
    <Copy SourceFiles="$(NuGetPackageRoot)lib.harmony\2.2.2\lib\net45\0Harmony.dll" DestinationFiles="$(MSBuildProjectDirectory)\lib\0Harmony.dll" SkipUnchangedFiles="true" Condition="Exists('$(NuGetPackageRoot)lib.harmony\2.2.2\lib\net45\0Harmony.dll')" />
  </Target>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RaftManaged)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(RaftManaged)\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(RaftManaged)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RaftManaged)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(RaftManaged)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(RaftManaged)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(RaftManaged)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(RaftManaged)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(RaftManaged)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
