// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqwyNk9KnREtjeaCFLtwZ4rhBd4uKKeKY',
    appId: '1:774291421347:android:75aa4f77a30c7371c56716',
    messagingSenderId: '774291421347',
    projectId: 'astral-game-6213b',
    storageBucket: 'astral-game-6213b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ2lekQFOm1KNUhk0qxCk0SGCRmV8wyrc',
    appId: '1:774291421347:ios:6a0bbd0d4996b1f1c56716',
    messagingSenderId: '774291421347',
    projectId: 'astral-game-6213b',
    storageBucket: 'astral-game-6213b.firebasestorage.app',
    iosBundleId: 'com.example.astralGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ2lekQFOm1KNUhk0qxCk0SGCRmV8wyrc',
    appId: '1:774291421347:ios:6a0bbd0d4996b1f1c56716',
    messagingSenderId: '774291421347',
    projectId: 'astral-game-6213b',
    storageBucket: 'astral-game-6213b.firebasestorage.app',
    iosBundleId: 'com.example.astralGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAH8Ss2A-7EMPlmDpnuQuGHMARexff1pI',
    appId: '1:774291421347:web:1907fbbf01b9edb7c56716',
    messagingSenderId: '774291421347',
    projectId: 'astral-game-6213b',
    authDomain: 'astral-game-6213b.firebaseapp.com',
    storageBucket: 'astral-game-6213b.firebasestorage.app',
    measurementId: 'G-DTY6CVKN09',
  );
}
